/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type $defs = Record<string, never>;
export interface components {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: {
    /** @description Access forbidden (invalid or expired signature) */
    Forbidden: {
      content: {
        /**
         * @example {
         *       "success": false,
         *       "error": {
         *         "message": "Invalid or expired signature",
         *         "code": 403
         *       },
         *       "timestamp": "2024-01-01T12:00:00+00:00"
         *     }
         */
        'application/json': components['schemas']['ErrorResponse'];
      };
      headers: Record<string, unknown>;
    };
    /** @description Resource not found */
    NotFound: {
      content: {
        /**
         * @example {
         *       "success": false,
         *       "error": {
         *         "message": "File not found",
         *         "code": 404
         *       },
         *       "timestamp": "2024-01-01T12:00:00+00:00"
         *     }
         */
        'application/json': components['schemas']['ErrorResponse'];
      };
      headers: Record<string, unknown>;
    };
    /** @description Internal server error */
    ServerError: {
      content: {
        /**
         * @example {
         *       "success": false,
         *       "error": {
         *         "message": "Internal server error",
         *         "code": 500
         *       },
         *       "timestamp": "2024-01-01T12:00:00+00:00"
         *     }
         */
        'application/json': components['schemas']['ErrorResponse'];
      };
      headers: Record<string, unknown>;
    };
    /** @description Authentication required or invalid API key */
    Unauthorized: {
      content: {
        /**
         * @example {
         *       "success": false,
         *       "error": {
         *         "message": "API key required. Provide X-API-Key header or Authorization: Bearer <key>",
         *         "code": 401
         *       },
         *       "timestamp": "2024-01-01T12:00:00+00:00"
         *     }
         */
        'application/json': components['schemas']['ErrorResponse'];
      };
      headers: Record<string, unknown>;
    };
    /** @description Validation error */
    ValidationError: {
      content: {
        /**
         * @example {
         *       "success": false,
         *       "error": {
         *         "message": "Missing required parameter",
         *         "code": 422,
         *         "errors": {
         *           "file": "File path is required"
         *         }
         *       },
         *       "timestamp": "2024-01-01T12:00:00+00:00"
         *     }
         */
        'application/json': components['schemas']['ErrorResponse'];
      };
      headers: Record<string, unknown>;
    };
  };
  schemas: {
    ErrorResponse: {
      error?: {
        /** @example 400 */
        code?: number;
        /**
         * @example {
         *       "file": "File path is required"
         *     }
         */
        errors?: Record<string, string>;
        /** @example Error message */
        message?: string;
      };
      /** @example false */
      success?: boolean;
      /**
       * Format: date-time
       * @example 2024-01-01T12:00:00+00:00
       */
      timestamp?: string;
    };
    FileInfoResponse: {
      data?: {
        /**
         * @description MIME type of the file
         * @example image/jpeg
         */
        mime_type?: null | string;
        /**
         * @description Unix timestamp of last modification
         * @example 1704067200
         */
        modified?: number;
        /**
         * @description File name
         * @example photo.jpg
         */
        name?: string;
        /**
         * @description Relative file path
         * @example images/photo.jpg
         */
        path?: string;
        /**
         * @description File size in bytes
         * @example 123456
         */
        size?: number;
      };
      /** @example true */
      success?: boolean;
      /**
       * Format: date-time
       * @example 2024-01-01T12:00:00+00:00
       */
      timestamp?: string;
    };
    HealthResponse: {
      data?: {
        /** @example ok */
        status?: string;
        /**
         * Format: date-time
         * @example 2024-01-01T12:00:00+00:00
         */
        timestamp?: string;
        /** @example 1.0.0 */
        version?: string;
      };
      /** @example true */
      success?: boolean;
      /**
       * Format: date-time
       * @example 2024-01-01T12:00:00+00:00
       */
      timestamp?: string;
    };
    SignedUrlResponse: {
      data?: {
        /**
         * @description Unix timestamp when the URL expires
         * @example 1704067200
         */
        expires_at?: number;
        /**
         * @description Number of seconds until expiration
         * @example 3600
         */
        expires_in?: number;
        /**
         * Format: uri
         * @description Signed URL for accessing the file
         * @example https://storage.imdat.dev/api/media/serve?file=images/photo.jpg&expires=1704067200&signature=abc123...
         */
        url?: string;
      };
      /** @example true */
      success?: boolean;
      /**
       * Format: date-time
       * @example 2024-01-01T12:00:00+00:00
       */
      timestamp?: string;
    };
  };
}
export interface operations {
  generateSignedUrl: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query: {
        /** @description Custom expiration time in seconds (default from config) */
        expires?: number;
        /** @description Relative path to file from storage_secure directory */
        file: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Signed URL generated successfully */
      200: {
        content: {
          /**
           * @example {
           *       "success": true,
           *       "data": {
           *         "url": "https://storage.imdat.dev/api/media/serve?file=images/photo.jpg&expires=1704067200&signature=abc123def456...",
           *         "expires_at": 1704067200,
           *         "expires_in": 3600
           *       },
           *       "timestamp": "2024-01-01T12:00:00+00:00"
           *     }
           */
          'application/json': components['schemas']['SignedUrlResponse'];
        };
        headers: Record<string, unknown>;
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      422: components['responses']['ValidationError'];
      500: components['responses']['ServerError'];
    };
  };
  getFileInfo: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query: {
        /** @description Relative path to file from storage_secure directory */
        file: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description File information */
      200: {
        content: {
          /**
           * @example {
           *       "success": true,
           *       "data": {
           *         "path": "images/photo.jpg",
           *         "name": "photo.jpg",
           *         "size": 123456,
           *         "mime_type": "image/jpeg",
           *         "modified": 1704067200
           *       },
           *       "timestamp": "2024-01-01T12:00:00+00:00"
           *     }
           */
          'application/json': components['schemas']['FileInfoResponse'];
        };
        headers: Record<string, unknown>;
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      422: components['responses']['ValidationError'];
    };
  };
  getHealth: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API is healthy */
      200: {
        content: {
          /**
           * @example {
           *       "success": true,
           *       "data": {
           *         "status": "ok",
           *         "timestamp": "2024-01-01T12:00:00+00:00",
           *         "version": "1.0.0"
           *       },
           *       "timestamp": "2024-01-01T12:00:00+00:00"
           *     }
           */
          'application/json': components['schemas']['HealthResponse'];
        };
        headers: Record<string, unknown>;
      };
    };
  };
  serveFile: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query: {
        /** @description Expiration timestamp (from signed URL) */
        expires: number;
        /** @description File path (from signed URL) */
        file: string;
        /** @description HMAC signature (from signed URL) */
        signature: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description File content */
      200: {
        content: {
          'application/pdf': string;
          'image/gif': string;
          'image/jpeg': string;
          'image/png': string;
          'image/webp': string;
          'video/mp4': string;
        };
        headers: {
          [name: string]: unknown;
          /** @description Cache control directive */
          'Cache-Control'?: string;
          /** @description File disposition (inline) */
          'Content-Disposition'?: string;
          /** @description File size in bytes */
          'Content-Length'?: number;
          /** @description MIME type of the file */
          'Content-Type'?: string;
        };
      };
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      422: components['responses']['ValidationError'];
    };
  };
}
export interface paths {
  '/api/media/info': {
    delete?: never;
    /**
     * Get file information
     * @description Returns metadata about a media file without downloading it.
     *
     *     **Authentication Required:** This endpoint requires a valid API key.
     */
    get: operations['getFileInfo'];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  '/api/media/serve': {
    delete?: never;
    /**
     * Serve file via signed URL
     * @description Serves a media file using a signed URL. This endpoint does not require
     *     API key authentication, but the signed URL must be valid and not expired.
     *
     *     The signed URL is obtained from `/api/media/sign` endpoint.
     */
    get: operations['serveFile'];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  '/api/media/sign': {
    delete?: never;
    /**
     * Generate signed URL
     * @description Generates a cryptographically signed URL for accessing a media file.
     *
     *     **Authentication Required:** This endpoint requires a valid API key.
     *
     *     The signed URL can be used to access the file via `/api/media/serve` without
     *     requiring authentication. Signed URLs expire after a configurable time period.
     */
    get: operations['generateSignedUrl'];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  '/health': {
    delete?: never;
    /**
     * Health check
     * @description Returns the API health status
     */
    get: operations['getHealth'];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
